### PR TITLE
RMMIS-5098: Fix checkable radio

### PR DESCRIPTION
**Pull request by traviscooperscdhhs**

### CODE REVIEW

**Comment by mallenscdhhs** [comment]
@traviscooperscdhhs looks like github doesnt allow for changing the branch a PR points to. This one should point to release/v1.1.2.

**Comment by traviscooperscdhhs** [comment]
When doing that, it's making the diff 47 files big. Have you merged from develop into 1.1.2?

**Comment by mallenscdhhs** [comment]
this fix was supposed to go in release/v1.1.2, which is a snapshot of develop *before* we started working on v1.2.0. So this changes needs to happen there.

**Comment by mallenscdhhs** [comment]
can you cherrypick your commit over to release/v1.1.2?

**Comment by traviscooperscdhhs** [comment]
yeah np

**Comment by mallenscdhhs** [comment]
Sorry about that, was probably an assumption on my part that you knew to do that. So, whenever we have two releases being worked on(1.1.2, 1.2.0) there will be a release branch cut to allow development to continue on the farthest version.

**Pull request closed without merging**
