### PR TITLE
Update Field, FieldLabel

### PR DESCRIPTION
**Pull request by mallenscdhhs**

### CODE REVIEW

**Comment by traviscooperscdhhs** [comment]
:+1:

**Comment by traviscooperscdhhs** [comment]
MERGETHISTHINGMAN

**Comment by kjschulz** [comment]
:+1: :100: NAILEDIT

**Comment by kjschulz** [comment]
BRINGTHEMERGE!

**Comment by traviscooperscdhhs** [comment]
(whyyouno) merge!

**Comment by mallenscdhhs** [comment]
Left out some key features, adding those in and writing tests

**Comment by traviscooperscdhhs** [comment]
Were you able to figure the testing of PASTE out?

**Comment by traviscooperscdhhs** [comment]
:+1:

**Pull request merged**
